name: iub_transport_system
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.16.0 <3.0.0"

#4.5.3
dependency_overrides:
  firebase_core_platform_interface: 4.5.1
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  modal_progress_hud_nsn: ^0.1.0-nullsafety-0
  firebase_core: ^1.10.0
  cloud_firestore:
  firebase_auth: ^3.2.0
  intl: ^0.17.0
  custom_marker: ^1.0.0
  location: ^4.3.0
  google_maps_flutter: ^2.1.1
  provider: ^6.0.2
  connectivity_plus:
  url_launcher: ^6.1.5
  font_awesome_flutter: ^10.1.0
  fluttertoast: 8.0.9
  animated_text_kit: ^4.2.0
  permission_handler: ^10.0.2
  flutter_switch: ^0.3.2
  geoflutterfire: ^3.0.1
  firebase_messaging: ^11.4.1
  flutter_local_notifications: ^9.4.0
  file_picker:
  firebase_storage:
  firebase_database: ^9.0.10
  syncfusion_flutter_pdfviewer: ^19.2.51
  path_provider: ^2.0.1
  flutter_app_badger: ^1.5.0
  get: ^4.6.5
  vibration: ^1.7.6
  dio: ^5.0.0

#  contactus: ^1.2.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:

  uses-material-design: true

  assets:
    - images/b2.png
    - images/bs.png
    - images/logo.png
    - images/admain.jpg
    - images/drr.png
    - images/bus.jpg
    - images/b2.png
    - images/dr.jpg
    - images/iub.png
    - images/stop.png
    - images/tools.png
    - images/traffic.png
    - images/iubBus.png
  fonts:
    - family: FiraSans
      fonts:
        - asset: fonts/FiraSans-BlackItalic.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
